const _girls: Girl[] = [
    new Girl('Shiro', Role.Bombmer),
    new Girl('Kuro', Role.Bombmer),
    new Girl('Shiori', Role.Bombmer),
    new Girl('Gray', Role.Bombmer),
    new Girl('Oran', Role.Ataccker),
    new Girl('Urushi', Role.Ataccker),
    new Girl('Sepia', Role.Ataccker),
    new Girl('Emera', Role.Shooter),
    new Girl('Puple', Role.Shooter),
    new Girl('Tsugaru', Role.Shooter),
    new Girl('Momoko', Role.Blocker),
    new Girl('Aqua', Role.Blocker),
    new Girl('GrimAloe', Role.Blocker),
];