const _player_ranks = [
    new PlayerRank(RankClass.Beginner, RankLevel.C),
    new PlayerRank(RankClass.Beginner, RankLevel.B),
    new PlayerRank(RankClass.Beginner, RankLevel.A),
    new PlayerRank(RankClass.Rookie, RankLevel.C),
    new PlayerRank(RankClass.Rookie, RankLevel.B),
    new PlayerRank(RankClass.Rookie, RankLevel.A),
    new PlayerRank(RankClass.Regular, RankLevel.C),
    new PlayerRank(RankClass.Regular, RankLevel.B),
    new PlayerRank(RankClass.Regular, RankLevel.A),
    new PlayerRank(RankClass.Star, RankLevel.C),
    new PlayerRank(RankClass.Star, RankLevel.B),
    new PlayerRank(RankClass.Star, RankLevel.A),
    new PlayerRank(RankClass.SuperStar, RankLevel.C),
    new PlayerRank(RankClass.SuperStar, RankLevel.B),
    new PlayerRank(RankClass.SuperStar, RankLevel.A),
    new PlayerRank(RankClass.Master, RankLevel.C),
    new PlayerRank(RankClass.Master, RankLevel.B),
    new PlayerRank(RankClass.Master, RankLevel.A),
]