import { Stage, BaseStage } from './../../scripts/record/stage';

export const _stages: Stage[] = [
    new Stage(BaseStage.BomTown, '1'),
    new Stage(BaseStage.BomTown, '2'),
    new Stage(BaseStage.BomTown, '2.1'),
    new Stage(BaseStage.BomTown, '3'),
    new Stage(BaseStage.BomTown, '4'),
    new Stage(BaseStage.BomTown, '5'),
    new Stage(BaseStage.PanicIsland, '1'),
    new Stage(BaseStage.PanicIsland, '2'),
    new Stage(BaseStage.PanicIsland, '3'),
    new Stage(BaseStage.PanicIsland, '1'),
    new Stage(BaseStage.CyberSpace, '2'),
    new Stage(BaseStage.CyberSpace, '3'),
    new Stage(BaseStage.CyberSpace, '4'),
    new Stage(BaseStage.QMABomTown, ''),
    new Stage(BaseStage.HalloweenTown, '1'),
    new Stage(BaseStage.HalloweenTown, '2'),
    new Stage(BaseStage.ChristmasTown, '1'),
    new Stage(BaseStage.ChristmasTown, '1'),
    new Stage(BaseStage.TheKAC8thQualifier, ''),
    new Stage(BaseStage.TheKAC8thFinals, ''),
    new Stage(BaseStage.CastleOfAquaBlue, '1'),
    new Stage(BaseStage.CastleOfAquaBlue, '2'),
    new Stage(BaseStage.CastleOfAquaBlue, '3'),
];
